-- CREATE DATABASE ELECTION;

CREATE SCHEMA E_SCHEMA;

CREATE TABLE E_SCHEMA.TWEET(
   T_ID INT PRIMARY KEY,
   HANDLE         TEXT    NOT NULL,
   INHALT          TEXT     NOT NULL,
   ZEIT 			TIMESTAMP NOT NULL, 
   FAVORITE_COUNT INT NOT NULL,
   RETWEET_COUNT  INT NOT NULL,
   IN_REPLY_TO 	  TEXT,
   SOURCE_URL     TEXT
);

CREATE TABLE E_SCHEMA.HASHTAG(
	H_ID INT PRIMARY KEY,
	NAME TEXT NOT NULL,
	ABS_HAUF INT
);

CREATE TABLE E_SCHEMA.ENTHAELT(
	F_T_ID INT REFERENCES E_SCHEMA.TWEET(T_ID),
	F_H_ID INT REFERENCES E_SCHEMA.HASHTAG(H_ID),
	PRIMARY KEY (F_T_ID, F_H_ID)
);

CREATE TABLE E_SCHEMA.PAARWEISE(
	P_HAUF INT,
	F_H_ID1 INT REFERENCES E_SCHEMA.HASHTAG(H_ID),
	F_H_ID2 INT REFERENCES E_SCHEMA.HASHTAG(H_ID),
	PRIMARY KEY (F_H_ID1, F_H_ID2)
);
